export type BoardGame = {
  id: string;
  title: string;
  subtitle?: string;
  price: number;
  oldPrice?: number;
  playersMin: number;
  playersMax: number;
  ageMin: number;
  playTimeMin: number;
  playTimeMax: number;
  genres: string[];
  publisher: string;
  description: string;
  shortDescription: string;
  images: string[];
  inStock: boolean;
  isBestseller?: boolean;
  isNew?: boolean;
  tags: string[];
};
